name: surfel_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ffmpeg
  - pillow
  - pip
  - cuda-toolkit=12.1
  - gcc_linux-64=11.2
  - plyfile
  - python=3.10
  - "numpy<2"
  - pytorch=2.4
  - torchaudio=2.4
  - torchvision=0.19
  - typing_extensions=4.9.0
  - pip:
    - opencv-python
    - open3d==0.18.0
    - mediapy==1.1.2
    - lpips==0.1.4
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - submodules/diff-surfel-rasterization
    - submodules/simple-knn